services:
    api:
        build:
            context: ./api/Presentation
        ports:
            - 81:81
        volumes:
            - './api/Presentation/:/app/'
        depends_on:
            - rabbit
            - mongo
    
    eventbushandler:
        build:
            context: ./api/EventBusHandler
        volumes:
            - './api/EventBusHandler/:/app/'
        depends_on:
            - rabbit
            - mongo
    
    front:
        build:
            context: ./web
        ports:
            - 80:80
        environment:
            - PORT=80
            - WATCHPACK_POLLING=true
        volumes:
            - './web/:/app/'
        depends_on:
            - api
    
    rabbit:
        image: rabbitmq:3-management
        ports:
            - 5671:5671
            - 5672:5672
            - 15672:15672
    
    mongo:
        image: mongo
        ports:
            - 27017:27017
    